pointcloud_to_laserscan:
  ros__parameters:
    target_frame: base_link  # o velodyne_link, según tu TF
    transform_tolerance: 0.01
    min_height: -0.1
    max_height: 0.2
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.0087
    scan_time: 0.1
    range_min: 0.1
    range_max: 10.0
    use_inf: true
    inf_epsilon: 1.0
    # Puedes aplicar un filtro a Z para evitar puntos del suelo o techos
